#!/bin/bash
[[ -z $1 ]] && echo "./bootcentos <name>" && exit 1
gcloud compute instances create $1 --image centos-7 --machine-type n1-highcpu-4 --metadata-from-file startup-script=centos/cloud-centos-7.sh
